name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update WakaTime stats
        uses: anmol098/waka-readme-stats@v3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_TITLE: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
