name: Update Dynamic README Profile (With WakaTime)

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4
        with:
          # Use Personal Access Token instead of GITHUB_TOKEN for WakaTime
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: ⏰ Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Use Personal Access Token for better permissions
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          COMMIT_BY_ME: "True"
          
      - name: 🎯 Update Dynamic Quote
        run: |
          # Simple quote update
          QUOTES=(
            "Code never lies, comments sometimes do.|Ron Jeffries"
            "First, solve the problem. Then, write the code.|John Johnson"
            "Any fool can write code that a computer can understand.|Martin Fowler"
            "Programming isn't about what you know; it's about what you can figure out.|Chris Pine"
            "The best error message is the one that never shows up.|Thomas Fuchs"
          )
          
          RANDOM_INDEX=$((RANDOM % ${#QUOTES[@]}))
          IFS='|' read -r QUOTE AUTHOR <<< "${QUOTES[$RANDOM_INDEX]}"
          
          # Update the quote in README
          sed -i "s|> \*\".*\"\*|> \*\"$QUOTE\"\*|g" README.md
          sed -i "s|> \*\*— .*\*\*|> \*\*— $AUTHOR\*\*|g" README.md
          
          echo "Updated quote: $QUOTE - $AUTHOR"
          
      - name: 📅 Update Timestamp
        run: |
          TIMESTAMP=$(date -u +"%B %d, %Y at %H:%M UTC")
          sed -i "s|Last updated: .*|Last updated: $TIMESTAMP|g" README.md
          echo "Updated timestamp: $TIMESTAMP"
          
      - name: 🔍 Check for Changes
        id: verify_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            git diff --stat
          fi
          
      - name: 💾 Commit Updates
        if: steps.verify_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "🤖 Auto-update README: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
          echo "✅ README updated successfully!"